CREATE TABLE IF NOT EXISTS Student (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    prn VARCHAR(20) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Student (name, prn) VALUES 
('MAYUR', '23510014'),
('ALICE', '23510015')
ON CONFLICT (prn) DO NOTHING;

SELECT * FROM Student